### ISSUE TITLE
Evaluate: How to handle JavaScript objects in Elm.

### ISSUE THREAD

**Issue by jan-christiansen** [Frederik-Hamester/legislative-bargaining-lab#3]

**Comment by jan-christiansen** [comment]
Please always write some lines about your results. Because I am currently supervising lots of projects I am lost otherwise.

**Comment by Frederik-Hamester** [comment]
There were problems decoding the JoinTree data structure in Elm.
The first problem was that the type was recursive. This problem can be handled by the lazy function.
The second problem was that the BoolOr and BoolAnd nodes could not be distinguished by an elm decoder since their names were not shown in the Json code, and they head the same properties.
This problem can be handled by adding an id string to one of the nodes before it is pared to Json.
